# Dockerfile for the web frontend
# Used for https://github.com/javouhey/airquality

FROM ubuntu:precise
MAINTAINER Gavin Bong <rubycoder@gmail.com>

# TBD - nothing here yet

RUN apt-get clean

CMD ["/usr/bin/supervisord", "-n", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
